export const GET_POKEMONS = "GET_POKEMONS";
export const FILTER_POKEMONS = "FILTER_POKEMONS";
export const ORDER_NAME = "ORDER_POKEMONS";
export const ORDER_ATACK = "ORDER_ATACK";
export const ORDER_CREATION = "ORDER_CREATION";
export const GET_BY_NAME = "GET_BY_NAME";
export const GET_COPY_POKEMONS = "GET_COPY_POKEMONS";
export const POST_POKEMON = "POST_POKEMON";